### ISSUE TITLE
FTS build

### ISSUE THREAD

**Issue by TWiStErRob** [little-brother/sqlite-wlx#1]
I would like to use this on DBs with FTS3/4 tables.

Currently I get this error when opening a `create virtual table using fts3`
![image](https://github.com/little-brother/sqlite-wlx/assets/2906988/ca1b23f5-14b7-4a85-bec5-df61cbb54966)

**Comment by little-brother** [comment]
[Here](https://github.com/little-brother/sqlite-wlx/files/13205679/sqlite-wlx-1.1.3-fts.zip) is a version with FST3/4 support. Please check it.
I just added `-DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS` to [opts](https://github.com/little-brother/sqlite-wlx/wiki#how-to-build)-string.

P.S. Keep in mind the plugin doesn't have ICU support and therefore you might encouter with an incorrect behaviour with lower/upper cases for national chars.

**Comment by TWiStErRob** [comment]
Nice, thanks, it works now. Totally forgot I could just compile my own 😅
