### ISSUE TITLE
sqlite-wcx

### ISSUE THREAD

**Issue by TWiStErRob** [little-brother/sqlite-wlx#2]
Hey, I have an idea: create a sibling project for sqlite-wcx.
When entering an sqlite file the the following structure could be presented:

 * Tables
   * Table1
     * .schema (F3 would shown DDL like it does in wlx except in Lister, not a message box)
     * .triggers
       * trigger1
       * trigger2
     * .indexes
       * index1
     * row1 (F3 could show a record like `col1: val1\ncol2: val2\ncol3 ...`)
     * row2
     * ...
   * Table2
   * Table3
 * Views
   * ...
 * Triggers
   * Trigger_name (F3 would open definition)
 * Indexes
 * ...

For each table when entering that folder! it could show the rows of the table as "files". Since TCmd is already table view, we would get column reordering, filtering, sorting for free!

Additionally each row could be a folder too and the files would be the columns. The file contents inside the row folder would be the data. This could enable viewing blobs as image/etc., and all the power of WLX, and WCX (Ctrl+PgDn)!

What do you think about this?

**Comment by little-brother** [comment]
Hi, 

Thanks for the idea but I have to refuse it the following reasons:
1. I don't know how to code `wcx`
2. I'm not sure that it will be usefull.
3. Tables can contains many rows (1M+). Most likely TC will fall when trying to view these tables. `sqlite-wlx` loads only `2000` rows (see `cache-size` in ini-file) and that is why it can open 1M+ tables easily. I suppose there is no mechanism in `wcx` to load the list in parts.
